# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Day1-Helloworld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Texture'
  # Pods for Day1-Helloworld

  target 'Day1-HelloworldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Day1-HelloworldUITests' do
    # Pods for testing
  end

end
